/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package health4time;

import Login.Login;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//Clases importadas para imprimir (Boton Imprimir)
import java.awt.print.PrinterException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 3PY37LA_RS6
 */
public class Datos extends javax.swing.JFrame {

    private JFrame frame;
    List<MedicamentoNuevo> medicamento = new ArrayList<MedicamentoNuevo>();

    String medicamento1;
    String numRefe1;
    String dosis1;
    String noTabletas1;
    String lote1;
    String fechaEmi1;
    String fechaExpi1;
    String dosisDiaria1;
    String eSecun1;
    String masInfo1;
    String avisoAlm1;
    String manejoMa1;
    String manejoMedi1;

    /**
     * Creates new form Datos
     */
    public Datos() {
        initComponents();
        jcmbListaMedi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Selecciona", "Paracetamol", "Agregar"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtRecetaMedica = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnBorrar = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnReseta = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jcmbListaMedi = new javax.swing.JComboBox<>();
        jtxtRefe = new javax.swing.JTextField();
        jtxtDosis = new javax.swing.JTextField();
        jtxtNumeroDeTabletas = new javax.swing.JTextField();
        jtxtLote = new javax.swing.JTextField();
        jtxtEmision = new javax.swing.JTextField();
        jtxtExpiracion = new javax.swing.JTextField();
        jtxtDosisD = new javax.swing.JTextField();
        jtxtEfec = new javax.swing.JTextField();
        jtxtExtra = new javax.swing.JTextField();
        jtxtStock = new javax.swing.JTextField();
        jtxtMaquinas = new javax.swing.JTextField();
        jtxtManejoMe = new javax.swing.JTextField();
        jtxtIde = new javax.swing.JTextField();
        jtxtNss = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jtxtNacimiento = new javax.swing.JTextField();
        jtxtDireccion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(235, 255, 255));
        setFont(new java.awt.Font("Agency FB", 0, 11)); // NOI18N
        setLocation(new java.awt.Point(80, 80));
        setMinimumSize(new java.awt.Dimension(1250, 650));
        setPreferredSize(new java.awt.Dimension(1250, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 60)); // NOI18N
        jLabel1.setText("Health 4 Time");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, -10, 520, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1180, 60));

        jPanel2.setBackground(new java.awt.Color(189, 255, 194));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 255, 194), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtRecetaMedica.setColumns(20);
        jtxtRecetaMedica.setRows(5);
        jScrollPane1.setViewportView(jtxtRecetaMedica);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 390));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 380, 410));

        jPanel3.setBackground(new java.awt.Color(189, 255, 194));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 255, 204), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 38)); // NOI18N
        jLabel2.setText("Receta Del Paciente");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 520, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 800, 60));

        jPanel4.setBackground(new java.awt.Color(189, 255, 194));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 255, 194), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel4.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 80, 30));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel4.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 80, 30));

        btnReseta.setText("Receta");
        btnReseta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetaActionPerformed(evt);
            }
        });
        jPanel4.add(btnReseta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 90, 30));

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel4.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 110, 30));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel4.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 80, 30));

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel4.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 110, 30));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel4.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 110, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 1180, 60));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Medicamento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 110, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("No.Referencias");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Dosis (mg)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("No. de tabletas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Lote");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Fecha de emision ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Fecha de expiracion");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Dosis diaria");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Efectos secudarios");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 220, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Mas informacion");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Aviso de almacenamiento");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Manejo o uso de maquinas");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Manejo de medicamento");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("ID paciente");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("NSS");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Nombre del paciente");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Fecha de nacimiento");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Direccion");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 220, -1));

        jcmbListaMedi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcmbListaMedi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Paracetamol", "AUMN" }));
        jcmbListaMedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbListaMediActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbListaMedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 130, -1));

        jtxtRefe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtRefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 130, -1));

        jtxtDosis.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtDosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 130, -1));

        jtxtNumeroDeTabletas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtNumeroDeTabletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 130, -1));

        jtxtLote.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 130, -1));

        jtxtEmision.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtEmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 130, -1));

        jtxtExpiracion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtExpiracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 130, -1));

        jtxtDosisD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtDosisD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 130, -1));

        jtxtEfec.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtEfec, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 130, -1));

        jtxtExtra.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 130, -1));

        jtxtStock.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 130, -1));

        jtxtMaquinas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtMaquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 130, -1));

        jtxtManejoMe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtManejoMe, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 130, -1));

        jtxtIde.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtIde, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 130, -1));

        jtxtNss.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtNss, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 130, -1));

        jtxtNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 130, -1));

        jtxtNacimiento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 130, -1));

        jtxtDireccion.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jtxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 130, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicamento", "No.Referencias", "Dosis (mg)", "No. de tabletas", "Lote", "Fecha de emision", "Fecha de expiracion", "Dosis diaria", "Efectos secundarios", "Mas informacion", "Aviso de almacenamiento", "Manejo o uso de maquinas", "Manejo de medicamento", "ID paciente", "NSS", "Nombre del paciente", "Fecha de nacimiento", "Direccion"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 1180, 250));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Health 4 time.png"))); // NOI18N
        jLabel22.setText("jLabel22");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame, "Confirma si quieres salir", "Health 4 Time", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        try {
            jtxtRecetaMedica.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Datos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void jcmbListaMediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbListaMediActionPerformed

        if (jcmbListaMedi.getSelectedItem().equals("Paracetamol")) {
            //Columna 1 de informacion
            jtxtRefe.setText("Parace210203");
            jtxtDosis.setText("500 mg");
            jtxtNumeroDeTabletas.setText("50");
            jtxtLote.setText("321654");
            jtxtEmision.setText("05/12/2022");
            jtxtExpiracion.setText("06/12/2022");
            jtxtDosisD.setText("3");
            jtxtEfec.setText("Muerte");

            //Columna 2 de informacion
            jtxtExtra.setText("Mas en bodega");
            jtxtStock.setText("20 cajas");
            jtxtMaquinas.setText("No");
            jtxtManejoMe.setText("Beber con agua");
            jtxtIde.setText("");
            jtxtNss.setText("");

        } else if (jcmbListaMedi.getSelectedItem().equals("Selecciona")) {
            //Columna 1 de informacion
            jtxtRefe.setText("");
            jtxtDosis.setText("");
            jtxtNumeroDeTabletas.setText("");
            jtxtLote.setText("");
            jtxtEmision.setText("");
            jtxtExpiracion.setText("");
            jtxtDosisD.setText("");
            jtxtEfec.setText("");

            //Columna 2 de informacion
            jtxtExtra.setText("");
            jtxtStock.setText("");
            jtxtMaquinas.setText("");
            jtxtManejoMe.setText("");
            jtxtIde.setText("");
            jtxtNss.setText("");
            jtxtRecetaMedica.setText("");
            
        }else if (jcmbListaMedi.getSelectedItem().equals("Agregar")) {
            medicamento1 = JOptionPane.showInputDialog(null, "Introduce el medicamento");
            numRefe1 = JOptionPane.showInputDialog(null, "Introduce el numero de referencia");
            dosis1 = JOptionPane.showInputDialog(null, "Introduce la dosis");
            noTabletas1 = JOptionPane.showInputDialog(null, "Numero de tabletas");
            lote1 = JOptionPane.showInputDialog(null, "Introduce el lote");
            fechaEmi1 = JOptionPane.showInputDialog(null, "Introduce la fecha de emision");
            fechaExpi1 = JOptionPane.showInputDialog(null, "Introduce la fecha de expiracion ");
            dosisDiaria1 = JOptionPane.showInputDialog(null, "Introduce la dosis diaria");
            eSecun1 = JOptionPane.showInputDialog(null, "Introduce el efecto secundario");
            masInfo1 = JOptionPane.showInputDialog(null, "Introduce mas informacion");
            avisoAlm1 = JOptionPane.showInputDialog(null, "Introduce cuantas piezas se tienen");
            manejoMa1 = JOptionPane.showInputDialog(null, "¿Manejo o uso de maquinas");
            manejoMedi1 = JOptionPane.showInputDialog(null, "Manejo de medicamento");

            medicamento.add(new MedicamentoNuevo(medicamento1, numRefe1, dosis1, noTabletas1, lote1, fechaEmi1,
                    fechaExpi1, dosisDiaria1, eSecun1, masInfo1, avisoAlm1, manejoMa1, manejoMedi1));

            if ("Agregar" != medicamento1) {
            jcmbListaMedi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Selecciona", "Paracetamol", medicamento1, "Agregar"}));
            
            jtxtRefe.setText(numRefe1);
            jtxtDosis.setText(dosis1);
            jtxtNumeroDeTabletas.setText(noTabletas1);
            jtxtLote.setText(lote1);
            jtxtEmision.setText(fechaEmi1);
            jtxtExpiracion.setText(fechaExpi1);
            jtxtDosisD.setText(dosisDiaria1);
            jtxtEfec.setText(eSecun1);
           
           //Columna 2 de informacion
            jtxtExtra.setText(masInfo1);
            jtxtStock.setText(avisoAlm1);
            jtxtMaquinas.setText(manejoMa1);
            jtxtManejoMe.setText(manejoMedi1);
            jtxtIde.setText("");
            jtxtNss.setText("");
            jtxtRecetaMedica.setText(""); 
            }
            
        }


    }//GEN-LAST:event_jcmbListaMediActionPerformed

    private void btnResetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetaActionPerformed
        String variable1 = (jtxtRefe.getText());
        String variable2 = (jtxtDosis.getText());
        String variable3 = (jtxtNumeroDeTabletas.getText());
        String variable4 = (jtxtLote.getText());

        String variable5 = (jtxtDosisD.getText());
        String variable6 = (jtxtEfec.getText());
        String variable7 = (jtxtExtra.getText());

        String variable8 = (jtxtManejoMe.getText());
        String variable9 = (jtxtIde.getText());
        String variable10 = (jtxtNombre.getText());
        String variable11 = (jtxtNacimiento.getText());
        String variable12 = (jtxtNss.getText());
        String variable13 = "";

        if (jcmbListaMedi.getSelectedItem().equals("Paracetamol")) {
            variable13 = "Paracetamol";
        }else if(jcmbListaMedi.getSelectedItem().equals(medicamento1)) {
            variable13 = medicamento1;
        }

        jtxtRecetaMedica.setText("");
        jtxtRecetaMedica.append("\n\t                  Health 4 Time        \n"
                + "\n Nombre del paciente\t\t" + variable10
                + "\n Fecha de nacimiento\t\t" + variable11
                + "\n Numero de seguro social\t\t" + variable12
                + "\n Nombre del medicamento\t\t" + variable13
                + "\n Numero de referencia del medicamento\t" + variable1
                + "\n Dosis del medicamento\t\t" + variable2
                + "\n Numero de tabletas\t\t" + variable3
                + "\n Lote del medicamento\t\t" + variable4
                + "\n Dosis diaria\t\t\t" + variable5
                + "\n Efectos secundarios\t\t" + variable6
                + "\n Mas informacion\t\t" + variable7
                + "\n Formas de tomar medicamento\t" + variable8
                + "\n Numero de ID\t\t\t" + variable9
                + "\n\n\t Instrucciones que le asignamos");

        /* String variable15 = (jtxtRefe.getText());
         String variable16 = (jtxtRefe.getText());
         String variable17 = (jtxtRefe.getText());*/

    }//GEN-LAST:event_btnResetaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        jtxtRefe.setText("");
        jtxtDosis.setText("");
        jtxtNumeroDeTabletas.setText("");
        jtxtLote.setText("");
        jtxtEmision.setText("");
        jtxtExpiracion.setText("");
        jtxtDosisD.setText("");
        jtxtEfec.setText("");

        //Columna 2 de informacion
        jtxtExtra.setText("");
        jtxtStock.setText("");
        jtxtMaquinas.setText("");
        jtxtManejoMe.setText("");
        jtxtIde.setText("");
        jtxtNss.setText("");
        jtxtRecetaMedica.setText("");
        jcmbListaMedi.getModel().setSelectedItem("Selecciona");
        jtxtNombre.setText("");
        jtxtNacimiento.setText("");
        jtxtDireccion.setText("");


    }//GEN-LAST:event_btnResetActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Login ilogin = new Login();
        ilogin.setVisible(true);


    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{jcmbListaMedi.getSelectedItem().toString(),
            jtxtRefe.getText(), jtxtDosis.getText(), jtxtNumeroDeTabletas.getText(), jtxtLote.getText(),
            jtxtEmision.getText(), jtxtExpiracion.getText(), jtxtDosisD.getText(),
            jtxtEfec.getText(), jtxtExtra.getText(), jtxtStock.getText(),
            jtxtMaquinas.getText(), jtxtManejoMe.getText(), jtxtIde.getText(), jtxtNss.getText(),
            jtxtNombre.getText(), jtxtNacimiento.getText(), jtxtDireccion.getText()

        });

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "No hay mas datos para eliminar", "Health 4 Time",
                        JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una fila para eliminar", "Health 4 Time",
                        JOptionPane.OK_OPTION);
            }
        } else {
            model.removeRow(jTable1.getSelectedRow());
        }


    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReseta;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcmbListaMedi;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtDosis;
    private javax.swing.JTextField jtxtDosisD;
    private javax.swing.JTextField jtxtEfec;
    private javax.swing.JTextField jtxtEmision;
    private javax.swing.JTextField jtxtExpiracion;
    private javax.swing.JTextField jtxtExtra;
    private javax.swing.JTextField jtxtIde;
    private javax.swing.JTextField jtxtLote;
    private javax.swing.JTextField jtxtManejoMe;
    private javax.swing.JTextField jtxtMaquinas;
    private javax.swing.JTextField jtxtNacimiento;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtNss;
    private javax.swing.JTextField jtxtNumeroDeTabletas;
    private javax.swing.JTextArea jtxtRecetaMedica;
    private javax.swing.JTextField jtxtRefe;
    private javax.swing.JTextField jtxtStock;
    // End of variables declaration//GEN-END:variables
}

class MedicamentoNuevo {

    private String medicamento;
    private String numRefe;
    private String dosis;
    private String noTabletas;
    private String lote;
    private String fechaEmi;
    private String fechaExpi;
    private String dosisDiaria;
    private String eSecun;
    private String masInfo;
    private String avisoAlm;
    private String manejoMa;
    private String manejoMedi;

    public MedicamentoNuevo(String medicamento, String numRefe, String dosis, String noTabletas, String lote, String fechaEmi, String fechaExpi, String dosisDiaria, String eSecun, String masInfo, String avisoAlm, String manejoMa, String manejoMedi) {
        this.medicamento = medicamento;
        this.numRefe = numRefe;
        this.dosis = dosis;
        this.noTabletas = noTabletas;
        this.lote = lote;
        this.fechaEmi = fechaEmi;
        this.fechaExpi = fechaExpi;
        this.dosisDiaria = dosisDiaria;
        this.eSecun = eSecun;
        this.masInfo = masInfo;
        this.avisoAlm = avisoAlm;
        this.manejoMa = manejoMa;
        this.manejoMedi = manejoMedi;
    }

    public String getMedicamento() {
        return medicamento;
    }

    public String getNumRefe() {
        return numRefe;
    }

    public String getDosis() {
        return dosis;
    }

    public String getNoTabletas() {
        return noTabletas;
    }

    public String getLote() {
        return lote;
    }

    public String getFechaEmi() {
        return fechaEmi;
    }

    public String getFechaExpi() {
        return fechaExpi;
    }

    public String getDosisDiaria() {
        return dosisDiaria;
    }

    public String geteSecun() {
        return eSecun;
    }

    public String getMasInfo() {
        return masInfo;
    }

    public String getAvisoAlm() {
        return avisoAlm;
    }

    public String getManejoMa() {
        return manejoMa;
    }

    public String getManejoMedi() {
        return manejoMedi;
    }

    public void setMedicamento(String medicamento) {
        this.medicamento = medicamento;
    }

    public void setNumRefe(String numRefe) {
        this.numRefe = numRefe;
    }

    public void setDosis(String dosis) {
        this.dosis = dosis;
    }

    public void setNoTabletas(String noTabletas) {
        this.noTabletas = noTabletas;
    }

    public void setLote(String lote) {
        this.lote = lote;
    }

    public void setFechaEmi(String fechaEmi) {
        this.fechaEmi = fechaEmi;
    }

    public void setFechaExpi(String fechaExpi) {
        this.fechaExpi = fechaExpi;
    }

    public void setDosisDiaria(String dosisDiaria) {
        this.dosisDiaria = dosisDiaria;
    }

    public void seteSecun(String eSecun) {
        this.eSecun = eSecun;
    }

    public void setMasInfo(String masInfo) {
        this.masInfo = masInfo;
    }

    public void setAvisoAlm(String avisoAlm) {
        this.avisoAlm = avisoAlm;
    }

    public void setManejoMa(String manejoMa) {
        this.manejoMa = manejoMa;
    }

    public void setManejoMedi(String manejoMedi) {
        this.manejoMedi = manejoMedi;
    }

}
